version: '3.8'



     
services:
  mysql:
    image: mysql:8.0
    container_name: bug-tracking-mysql-container
    hostname: mysql-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bug-tracker-api
      MYSQL_USER: bugtracker
      MYSQL_PASSWORD: root
    ports:
      - "5001:3306"